
CREATE TABLE PRODUCTO (
	P_ID INT IDENTITY NOT NULL PRIMARY KEY,
	P_NOMBRE VARCHAR(150) NOT NULL,
	P_DESCRIPCION VARCHAR(250),
	P_CATEGORIA_ID INT NOT NULL,
	P_IMAGEN_ID INT NOT NULL
)

CREATE TABLE CATEGORIA (
	C_ID INT IDENTITY NOT NULL PRIMARY KEY,
	C_DESCRIPCION VARCHAR(250) NOT NULL
)

CREATE TABLE PRODUCTO_IMAGEN(
	IMG_ID INT IDENTITY NOT NULL PRIMARY KEY,
	IMG_DATA VARBINARY(MAX) NOT NULL,
	IMG_NOMBRE VARCHAR (200) NOT NULL,
	IMG_EXTENSION VARCHAR(5) NOT NULL
)

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_CAT FOREIGN KEY (P_CATEGORIA_ID) REFERENCES CATEGORIA(C_ID)
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_IMG FOREIGN KEY (P_IMAGEN_ID) REFERENCES PRODUCTO_IMAGEN(IMG_ID)
