//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_IMAGEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO_IMAGEN()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public int IMG_ID { get; set; }
        public byte[] IMG_DATA { get; set; }
        public string IMG_NOMBRE { get; set; }
        public string IMG_EXTENSION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}
