//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int P_ID { get; set; }
        public string P_NOMBRE { get; set; }
        public string P_DESCRIPCION { get; set; }
        public int P_CATEGORIA_ID { get; set; }
        public int P_IMAGEN_ID { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual PRODUCTO_IMAGEN PRODUCTO_IMAGEN { get; set; }
    }
}
